services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "BeSpoked123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - sqldata:/var/lib/sqlserver/data

  api:
    build:
      context: ./backend
    ports:
      - "5001:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=BeSpoked;User Id=sa;Password=BeSpoked123!;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    environment:
      - API_URL=http://api:8080
    depends_on:
      - api

volumes:
  sqldata:
