// <auto-generated />
using System;
using BeSpoked.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeSpoked.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260606151436_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeSpoked.Core.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1 River St, Austin TX",
                            FirstName = "Tom",
                            LastName = "Walker",
                            Phone = "512-200-0001",
                            StartDate = new DateTime(2022, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Address = "9 Summit Dr, Denver CO",
                            FirstName = "Lisa",
                            LastName = "Park",
                            Phone = "303-200-0002",
                            StartDate = new DateTime(2022, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Address = "44 Creek Ln, Portland OR",
                            FirstName = "Carlos",
                            LastName = "Mendez",
                            Phone = "503-200-0003",
                            StartDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Address = "77 Lake Ave, Seattle WA",
                            FirstName = "Nina",
                            LastName = "Patel",
                            Phone = "206-200-0004",
                            StartDate = new DateTime(2021, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BeSpoked.Core.Entities.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BeginDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 10m,
                            EndDate = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            BeginDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 15m,
                            EndDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 3
                        },
                        new
                        {
                            Id = 3,
                            BeginDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 8m,
                            EndDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 2
                        });
                });

            modelBuilder.Entity("BeSpoked.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CommissionPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QtyOnHand")
                        .HasColumnType("int");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Manufacturer")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommissionPercentage = 5m,
                            Manufacturer = "Trek",
                            Name = "Apex Racer",
                            PurchasePrice = 800m,
                            QtyOnHand = 10,
                            SalePrice = 1499m,
                            Style = "Road"
                        },
                        new
                        {
                            Id = 2,
                            CommissionPercentage = 6m,
                            Manufacturer = "Specialized",
                            Name = "TrailBlazer Pro",
                            PurchasePrice = 1200m,
                            QtyOnHand = 7,
                            SalePrice = 2199m,
                            Style = "Mountain"
                        },
                        new
                        {
                            Id = 3,
                            CommissionPercentage = 4m,
                            Manufacturer = "Cannondale",
                            Name = "UrbanGlide 7",
                            PurchasePrice = 500m,
                            QtyOnHand = 15,
                            SalePrice = 899m,
                            Style = "Hybrid"
                        },
                        new
                        {
                            Id = 4,
                            CommissionPercentage = 5.5m,
                            Manufacturer = "Trek",
                            Name = "GravelKing X",
                            PurchasePrice = 950m,
                            QtyOnHand = 5,
                            SalePrice = 1799m,
                            Style = "Gravel"
                        },
                        new
                        {
                            Id = 5,
                            CommissionPercentage = 7m,
                            Manufacturer = "Giant",
                            Name = "SpeedDemon 900",
                            PurchasePrice = 1500m,
                            QtyOnHand = 3,
                            SalePrice = 2799m,
                            Style = "Road"
                        });
                });

            modelBuilder.Entity("BeSpoked.Core.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CommissionPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountApplied")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SalesDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SalespersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SalespersonId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommissionPercentage = 5m,
                            CustomerId = 1,
                            DiscountApplied = 10m,
                            ProductId = 1,
                            SalePrice = 1499m,
                            SalesDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            CommissionPercentage = 6m,
                            CustomerId = 2,
                            DiscountApplied = 0m,
                            ProductId = 2,
                            SalePrice = 2199m,
                            SalesDate = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 2
                        },
                        new
                        {
                            Id = 3,
                            CommissionPercentage = 4m,
                            CustomerId = 3,
                            DiscountApplied = 15m,
                            ProductId = 3,
                            SalePrice = 899m,
                            SalesDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 1
                        },
                        new
                        {
                            Id = 4,
                            CommissionPercentage = 5.5m,
                            CustomerId = 4,
                            DiscountApplied = 0m,
                            ProductId = 4,
                            SalePrice = 1799m,
                            SalesDate = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 3
                        },
                        new
                        {
                            Id = 5,
                            CommissionPercentage = 7m,
                            CustomerId = 1,
                            DiscountApplied = 0m,
                            ProductId = 5,
                            SalePrice = 2799m,
                            SalesDate = new DateTime(2024, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 2
                        },
                        new
                        {
                            Id = 6,
                            CommissionPercentage = 5m,
                            CustomerId = 2,
                            DiscountApplied = 8m,
                            ProductId = 1,
                            SalePrice = 1499m,
                            SalesDate = new DateTime(2024, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 3
                        });
                });

            modelBuilder.Entity("BeSpoked.Core.Entities.Salesperson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FirstName", "LastName", "Phone")
                        .IsUnique();

                    b.ToTable("Salespersons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "12 Elm St, Austin TX",
                            FirstName = "Alice",
                            LastName = "Chen",
                            Manager = "Bob Kraft",
                            Phone = "512-111-0001",
                            StartDate = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Address = "88 Oak Ave, Denver CO",
                            FirstName = "Marcus",
                            LastName = "Reyes",
                            Manager = "Bob Kraft",
                            Phone = "303-111-0002",
                            StartDate = new DateTime(2019, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Address = "5 Maple Rd, Portland OR",
                            FirstName = "Priya",
                            LastName = "Sharma",
                            Manager = "Bob Kraft",
                            Phone = "503-111-0003",
                            StartDate = new DateTime(2021, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Address = "200 Pine Blvd, Seattle WA",
                            FirstName = "Jake",
                            LastName = "Novak",
                            Manager = "Bob Kraft",
                            Phone = "206-111-0004",
                            StartDate = new DateTime(2018, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TerminationDate = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BeSpoked.Core.Entities.Discount", b =>
                {
                    b.HasOne("BeSpoked.Core.Entities.Product", "Product")
                        .WithMany("Discounts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BeSpoked.Core.Entities.Sale", b =>
                {
                    b.HasOne("BeSpoked.Core.Entities.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeSpoked.Core.Entities.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeSpoked.Core.Entities.Salesperson", "Salesperson")
                        .WithMany("Sales")
                        .HasForeignKey("SalespersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("Salesperson");
                });

            modelBuilder.Entity("BeSpoked.Core.Entities.Customer", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("BeSpoked.Core.Entities.Product", b =>
                {
                    b.Navigation("Discounts");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("BeSpoked.Core.Entities.Salesperson", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
